Add test scripts

diff --git a/test-regression b/test-regression
--- a/test-regression
+++ b/test-regression
@@ -1,8 +1,15 @@
 #!/bin/bash
 
-rm $1.out $1.tmp
 $TOCCATA_DIR/toccata $1 > $1.tmp &&
 awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "m.c"; next; } { print; }' $1.tmp > $1.c &&
 $CC -g -fno-objc-arc -o $1.out -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.o $1.c -lpthread &&
-./$1.out "${@:2}"
-
+./$1.out > /dev/null
+if [ $? -ne 0 ]
+then
+    echo
+    echo "FAIL!!" $1
+    echo
+    rm $1.out $1.tmp $1.c
+    exit 1
+fi
+rm $1.out $1.tmp $1.c
